spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentDB?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: UeOqt@8502
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
